// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("RedDog.Engine.TableStorage")]
[assembly: AssemblyDescriptionAttribute("An extension for RedDog.Engine that persists job events to TableStorage.")]
[assembly: AssemblyProductAttribute("Red Dog")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
namespace System
{
    internal static class AssemblyVersionInformation
    {
        internal const string Version = "1.0.0.0";
    }
}
