// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("RedDog.Engine")]
[assembly: AssemblyDescriptionAttribute("A job runner suited for running jobs in Microsoft Azure Worker Roles.")]
[assembly: AssemblyProductAttribute("Red Dog")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0.0";
    }
}
